language: node_js
node_js:
  - "4"
  - "6"
  - "7"

before_install:
  - sudo apt-get install g++ build-essential
  
install:
  - npm install -g npm@3
  - npm install -g coveralls
  - npm install

script:
  - npm test
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true # ignore coveralls error

# Allow Travis tests to run in containers.
sudo: false
